### ISSUE TITLE
Could we back manage standard `kubectl` args like -n

### ISSUE THREAD

**Issue by gbergere** [uberspot/kubectl-plugins#1]
Hello, 

Could we back manage standard `kubectl` args like -n (--namespace)?

I'm happy to contribute when I get some free time :)

Thanks

**Comment by gbergere** [comment]
As `-n` is already used for `name` we won't really be able to keep `-n|--namespace` from default `kubectl` CLI.

**Comment by uberspot** [comment]
You can rename the existing -n to whatever you want and just add the namespace there if needed.
